apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-flow-test-app-staging
  namespace: argocd
  labels:
    platform.io/app: cicd-flow-test-app
    platform.io/env: staging
    platform.io/subcomponent: argocd
    platform.io/dora-track: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/jfillman/gitops-cicd-flow-test-app.git
    targetRevision: main
    path: cicd-flow-test-app/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: app-cicd-flow-test-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
