apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-flow-test-app
  namespace: app-cicd-flow-test-app-staging
  annotations:
    platform.io/dora-git-revision: 9a681707827eaa6f4bec80e0f9b32e7e1b674483
    platform.io/dora-image: ghcr.io/jfillman/cicd-flow-test-app:1.0.15-9a68170
    platform.io/dora-flow-start-time: "2026-08-12T16:55:26.601560159Z"
    platform.io/dora-gitops-pr-url: https://github.com/jfillman/gitops-cicd-flow-test-app/pull/171
spec:
  replicas: 1
  selector:
    matchLabels: {app: cicd-flow-test-app}
  template:
    metadata:
      labels: {app: cicd-flow-test-app}
    spec:
      containers:
        - name: cicd-flow-test-app
          image: ghcr.io/jfillman/cicd-flow-test-app:1.0.15-9a68170 # placeholder - patched by release.yaml's open-release-pr Task
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet: {path: /healthz, port: 3000}
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: {path: /healthz, port: 3000}
            initialDelaySeconds: 3
