apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-flow-test-app
  namespace: app-cicd-flow-test-app-staging
  annotations:
    platform.io/dora-git-revision: ef3c1be18b495da1593ad64d4e13b3e8bb86818c
    platform.io/dora-image: ghcr.io/jfillman/cicd-flow-test-app:1.0.5-ef3c1be-annotest1786423195
    platform.io/dora-flow-start-time: "2026-08-11T04:40:16.110500449Z"
    platform.io/dora-gitops-pr-url: https://github.com/jfillman/gitops-cicd-flow-test-app/pull/158
spec:
  replicas: 1
  selector:
    matchLabels: {app: cicd-flow-test-app}
  template:
    metadata:
      labels: {app: cicd-flow-test-app}
    spec:
      containers:
        - name: cicd-flow-test-app
          image: ghcr.io/jfillman/cicd-flow-test-app:1.0.6-f2ac06c # placeholder - patched by release.yaml's open-release-pr Task
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet: {path: /healthz, port: 3000}
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: {path: /healthz, port: 3000}
            initialDelaySeconds: 3
