apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-flow-test-app
  namespace: app-cicd-flow-test-app-staging
  annotations:
    platform.io/dora-git-revision: ffb85d76c13689c395932e5122075874203f5b68
    platform.io/dora-image: ghcr.io/jfillman/cicd-flow-test-app:1.0.11-ffb85d7
    platform.io/dora-flow-start-time: "2026-08-12T07:28:46.847830276Z"
    platform.io/dora-gitops-pr-url: https://github.com/jfillman/gitops-cicd-flow-test-app/pull/163
spec:
  replicas: 1
  selector:
    matchLabels: {app: cicd-flow-test-app}
  template:
    metadata:
      labels: {app: cicd-flow-test-app}
    spec:
      containers:
        - name: cicd-flow-test-app
          image: ghcr.io/jfillman/cicd-flow-test-app:1.0.11-ffb85d7 # placeholder - patched by release.yaml's open-release-pr Task
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet: {path: /healthz, port: 3000}
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: {path: /healthz, port: 3000}
            initialDelaySeconds: 3
