apiVersion: batch/v1
kind: Job
metadata:
  name: platform-outcome-syncfail
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    platform.io/app: cicd-flow-test-app
    platform.io/subcomponent: outcome-hook
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      serviceAccountName: platform-outcome-hook
      restartPolicy: Never
      containers:
        - name: notify
          image: ghcr.io/jfillman/platform-cicd-toolbox:latest
          command: ["/opt/platform/lib/argocd-outcome-hook.sh"]
          env:
            - name: POD_NAMESPACE
              valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
            - { name: RELAY_URL, value: "http://10.89.0.2:30880/outcome/kind-prod" }
            - { name: APP_NAMESPACE, value: "app-cicd-flow-test-app-cicd" }
            - { name: APP_NAME, value: "cicd-flow-test-app" }
            - { name: ENV, value: "staging" }
            - { name: PHASE, value: "Failed" }
            - { name: GIT_URL, value: "https://github.com/jfillman/cicd-flow-test-app" }
            - { name: GIT_REVISION, value: "fd5e12c4bf75745a3ba4170a2ed634be6a198b4a" }
            - { name: FLOW_START_TIME, value: "2026-08-12T08:12:13.155192832Z" }
            - { name: PR_URL, value: "https://github.com/jfillman/gitops-cicd-flow-test-app/pull/168" }
            - { name: CONFIG_JSON_B64, value: "e30=" }
